# Regression tests (serial)

name: "Regression test"

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  make-d3q19-short:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure
      run: gcc --version
      run: cp config/github-gcc.mk config.mk
      run: make serial
      run: make
