# Regression tests (serial)

name: "Regression (serial)"

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  run-serial-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure
      run: gcc --version
